(issue #6354) fix format string in connector logs
log string with wrong format was previously added by::

    https://github.com/elego/connector/commit/a9d477925c69334f577cee3dadd3fb09987ba1df#diff-76de619e000e5fb5e2662206d2bdda99R350

that did cause the following error to be logged into the standard output::

   ValueError: unsupported format character ')' (0x29) at index 38
   Logged from file runner.py, line 363